language: python
matrix:
  include:
    - arch: arm64
      python: 2.7
    - arch: amd64
      python: 2.7
    - arch: arm64
      python: 3.7
    - arch: amd64
      python: 3.7
    - arch: arm64
      python: 3.8
    - arch: amd64
      python: 3.8
    - arch: amd64
      python: pypy
      before_install:
        # Workaround for dependency errors, probably due to https://github.com/z4r/python-coveralls/issues/66
      - pip install --upgrade --force-reinstall pytest-cov==2.5.0 
    - arch: amd64
      python: pypy3
      before_install:
        # Workaround for dependency errors, probably due to https://github.com/z4r/python-coveralls/issues/66
        - pip install --upgrade --force-reinstall pytest-cov==2.5.0 
    - arch: arm64
      python: 2.7
      env: COVERAGE='on'
    - arch: amd64
      python: 2.7
      env: COVERAGE='on'
    - arch: arm64
      python: 3.6
      env: COVERAGE='on'
    - arch: amd64
      python: 3.6
      env: COVERAGE='on'
install:
  - pip install -U -e .[develop]
script:
  # Guard against invalid escapes in strings, like '\s'.
  - python -We:invalid -m compileall -f mpmath -q
  - pycodestyle
  - |
    if [ -n "${COVERAGE}" ]; then
      py.test --cov mpmath
    else
      py.test
    fi
after_success: test -n "${COVERAGE}" && codecov
notifications:
  email: false
